/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_machineversion_terminal_NetReceiveThread */

#ifndef _Included_com_machineversion_terminal_NetReceiveThread
#define _Included_com_machineversion_terminal_NetReceiveThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_machineversion_terminal_NetReceiveThread_MIN_PRIORITY
#define com_machineversion_terminal_NetReceiveThread_MIN_PRIORITY 1L
#undef com_machineversion_terminal_NetReceiveThread_NORM_PRIORITY
#define com_machineversion_terminal_NetReceiveThread_NORM_PRIORITY 5L
#undef com_machineversion_terminal_NetReceiveThread_MAX_PRIORITY
#define com_machineversion_terminal_NetReceiveThread_MAX_PRIORITY 10L
/*
 * Class:     com_machineversion_terminal_NetReceiveThread
 * Method:    pictureProcess
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_com_machineversion_terminal_NetReceiveThread_pictureProcess
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
